Moved hallmark generation from heatwallet.com to local node fixed various typos add comments removed some debug logging

diff --git a/fire/fire_builder/fire_builder b/fire/fire_builder/fire_builder
--- a/fire/fire_builder/fire_builder
+++ b/fire/fire_builder/fire_builder
@@ -71,15 +71,6 @@ return 0
 while [[ $# -gt 0 ]]; do
 	key="$1"
 	case "$key" in
-		# This is a flag type option. Will catch either -f or --foo
-		# -f|--foo)
-		#FOO=1
-		#;;
-		# Also a flag type option. Will catch either -b or --bar
-		#-b|--bar)
-		#BAR=1
-		#;;
-		# This is an arg value type option. Will catch -u userName or --user userName
 		-u|--user)
 			shift # past the key and to the value
 			HEAT_USER="$1"
@@ -146,7 +137,6 @@ while [[ $# -gt 0 ]]; do
 			shift
 			MODE="$1"
 			;;
-			# This is an arg=value type option. Will catch -u=userName or --user=userName
 		-u=*|--user=*)
 			# No need to shift here since the value is part of the same string
 			HEAT_USER="${key#*=}"
@@ -249,43 +239,42 @@ case "$MODE" in
 			if id "$HEAT_USER" >/dev/null 2>&1; then
 				#user exists
 				#proceed
-				echo $HEAT_USER
+				echo "verified user"
 			else
 				#user does not exist
 				# quietly add a user without password
 				echo "adding user: $HEAT_USER"
-				sudo adduser --quiet --disabled-password --shell /bin/bash --home /home/$HEAT_USER --gecos "User" $HEAT_USER
+				sudo adduser --quiet --disabled-password --shell /bin/bash --home /home/$HEAT_USER --gecos "User" $HEAT_USER				
 				#if password was supplied, set user password
 				if [[ $PASSWORD = *[!\ ]* ]]; then
 					# set password
 					sudo echo "$HEAT_USER:$PASSWORD" | chpasswd
+					echo "password was not set, it will need to be set manually"
 				fi
 	
 			fi
-	#		#make sure home directory exists for user
-	#		if test -d /home/$HEAT_USER/;
-	# 		then
-	#    			#directory exists
-	#    			echo "home exists"
-	#		else
-	#   			#directory does not exist
-	#   			sudo mkdir /home/$HEAT_USER
-	#   			sudo chown -r  "$USER:$HEAT_USER" /home/$HEAT_USER
-	#		fi
 	
 			#make sure node ip is set, if not try to determine what it is
 			if [[ $IP_ADDRESS = *[!\ ]* ]]; then
 				#already set
-				echo "$IP_ADDRESS"
+				echo "IP Address is set. Using $IP_ADDRESS"
 			else
-				IP_ADDRESS=`curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'` &&
-				echo "IP ADDRESS: $IP_ADDRESS"
+				echo "IP Address was not set. Attempting to obtain public ip from myip.opendns.com"
+				#IP_ADDRESS=`curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'` &&
+				IP_ADDRESS=`dig +short myip.opendns.com @resolver1.opendns.com`
+				gotIp=$?
+				if [[ $gotIp ]]; then				
+					echo "Got public IP Address. Using $IP_ADDRESS"
+				else
+					echo "Error: Unable to get public IP Address!!! Exiting"
+					exit 1
+				fi
 			fi
 	
 			#Verify HEAT_ID (accountNumber in arguments)
 			if [[ $HEAT_ID = *[!\ ]* ]]; then
 				#already set
-				echo "$HEAT_ID"
+				echo "Heat Id was set. Using: $HEAT_ID"
 			else
 				echo "HEAT_ID was not set in this script or passed in as an argument (accountNumber). HEAT_ID is required. Exiting script."
 				exit 1
@@ -293,15 +282,14 @@ case "$MODE" in
 
 			##Verify and encode WALLET_SECRET
 			if [[ $WALLET_SECRET = *[!\ ]* ]]; then
-				echo "ws:$WALLET_SECRET"
 				#already set
 				#URI encode it
 				if [[ `echo $WALLET_SECRET | grep "%20"` ]]; then
-					echo "already encoded"
+					echo "Verified wallet secret"
 				else
+					echo "Encoding wallet secret"
 					ENCODED=$(urlencode "$WALLET_SECRET")
-					#WALLET_SECRET="$ENCODED"
-					echo $ENCODED
+					echo "Verified wallet secret"					
 				fi
 			else
 				echo "WALLET_SECRET was not set in this script or passed in as an argument. WALLET_SECRET IS REQUIRED. Exiting script."
@@ -313,7 +301,7 @@ case "$MODE" in
 			FS_LC=`echo "$FORCE_SCAN" | sed 's/.*/\L&/'`
 			if [[ "$FS_LC" == "true" || "$FS_LC" == "false" ]]; then
 				FORCE_SCAN="$FS_LC"
-				echo "Force Scan = $FORCE_SCAN"
+				echo "Force scan was set to $FORCE_SCAN"
 			else
 				echo "$FORCE_SCAN is invalid value for force scan. Valid values are true and false"
 				exit 1
@@ -324,7 +312,7 @@ case "$MODE" in
 			FV_LC=`echo $FORCE_VALIDATE | sed 's/.*/\L&/'`
 			if [[ "$FV_LC" == "true" || "$FV_LC" == "false" ]]; then
 				FORCE_VALIDATE="$FV_LC"
-				echo "Force validate = $FORCE_VALIDATE"
+				echo "Force validate was set to $FORCE_VALIDATE"
 			else
 				echo "$FORCE_VALIDATE is invalid value for force validate. Valid values are true and false"
 				exit 1
@@ -335,7 +323,7 @@ case "$MODE" in
 			US_LC=`echo $USE_SNAPSHOT | sed 's/.*/\L&/'`
 			if [[ "$US_LC" == "true" || "$US_LC" == "false" ]]; then
 				USE_SNAPSHOT="$US_LC"
-				echo "Use snapshot: $USE_SNAPSHOT"
+				echo "Use snapshot was set to $USE_SNAPSHOT"
 			else
 				echo "$USE_SNAPSHOT is invalid value for Download Snapshot (USE_SNAPSHOT). Valid values are true and false"
 				exit 1
@@ -345,7 +333,7 @@ case "$MODE" in
 			AU_LC=`echo $AUTO_UPGRADE | sed 's/.*/\L&/'`
 			if [[ "$AU_LC" == "true" || "$AU_LC" == "false" ]]; then
 				AUTO_UPGRADE=$AU_LC				
-				echo "Auto Upgrade: $AUTO_UPGRADE"
+				echo "Auto Upgrade was set to $AUTO_UPGRADE"
 			else
 				echo "$AUTO_UPGRADE is invalid value for autoUpgrade. Valid values are true and false"
 				exit 1
@@ -354,15 +342,10 @@ case "$MODE" in
 			if [[ $HALLMARK == *[!\ ]* ]]; then
 				#already set
 				hallmarkSet="true"
+				echo "hallmark was set"
 			else
+				echo "hallmark was not set, it will be obtained automatically later."
 				hallmarkSet="false"
-				#CURRENT_DATE=$(date +'%Y-%m-%d') &&
-#				HALLMARK_URL="https://heatwallet.com:7734/api/v1/tools/hallmark/encode/$IP_ADDRESS/200/$CURRENT_DATE/$ENCODED"
-#				echo "hallmark url: $HALLMARK_URL"
-#				HALLMARK_RESPONSE=`curl -X GET --header 'Accept: application/json' $HALLMARK_URL` &&
-#				echo "hallmark response: $HALLMARK_RESPONSE"
-#				HALLMARK=`echo "$HALLMARK_RESPONSE" | cut -c14- | rev | cut -c3- | rev` &&
-#				echo "HALLMARK: $HALLMARK"
 			fi
 	
 			#update repos and packages and install dependencies
@@ -379,7 +362,7 @@ case "$MODE" in
 			sudo apt-get install -y curl &&
 			sudo apt-get install -y jq && #to parse JSON
 			sudo apt-get install -y bc && #for math
-			sudo apt-get install -y dbus #needed for some installs, not sure why its missing in those variations, need to investigate further, I believe the script may be starting before dbus was all the way up
+			sudo apt-get install -y dbus #needed for some installs, not sure why its missing in those variations, need to investigate further, I believe the script may be starting before dbus was all the way up			
 			#sudo apt-get install -y dialog #for UI, may move this
 			#sudo apt-get install -y #some version of curses maybe for UI?
 			
@@ -499,9 +482,6 @@ case "$MODE" in
 				heat.forceScan=$FORCE_SCAN
 				heat.forceValidate=$FORCE_VALIDATE
 			" > $CONF
-	#remove following from conf creation above
-	#heat.myHallmark=$HALLMARK
-	#will be added later after a check
 	
 			#save install vars
 			echo "$AUTO_UPGRADE" > "$SHARED/dat/autoUpgrade"
@@ -510,7 +490,6 @@ case "$MODE" in
 			echo "$(date)" > "$SHARED/dat/install_time"
 			echo "$IP_ADDRESS" > "$SHARED/dat/ipAddress"
 			echo "$MAX_PEERS" > "$SHARED/dat/maxPeers"
-			#echo "$HALLMARK" > "$SHARED/dat/hallmark"
 			echo "$FORCE_SCAN" > "$SHARED/dat/forceScan"
 			echo "$FORCE_VALIDATE" > "$SHARED/dat/forceValidate"
 			echo "$USE_SNAPSHOT" > "$SHARED/dat/useSnapshot"
@@ -527,8 +506,8 @@ case "$MODE" in
 			fb_wd="WorkingDirectory=$FIRE_HOME/fire_builder"
 			fb_st="ExecStart=$FIRE_HOME/fire_builder/fire_builder"
 			svc_user="User=$HEAT_USER"
-			#fb_sp=
-			#fb_rs=
+			#fb_sp= #included for future use
+			#fb_rs= #included for future use
 			sed -i "/WorkingDirectory/c $fw_wd" "$FIRE_HOME/fire_watch/fire_watch.service"
 			sed -i "/ExecStart/c $fw_st" "$FIRE_HOME/fire_watch/fire_watch.service"
 			sed -i "/ExecStop/c $fw_sp" "$FIRE_HOME/fire_watch/fire_watch.service"
@@ -537,8 +516,8 @@ case "$MODE" in
 	
 			sed -i "/WorkingDirectory/c $fb_wd" "$FIRE_HOME/fire_builder/fire_builder.service"
 			sed -i "/ExecStart/c $fb_st" "$FIRE_HOME/fire_builder/fire_builder.service"
-			#sed -i "/WorkingDirectory/c $fb_sp" "$FIRE_HOME/fire_builder/fire_builder.service"
-			#sed -i "/WorkingDirectory/c $fb_rs" "$FIRE_HOME/fire_builder/fire_builder.service"
+			#sed -i "/WorkingDirectory/c $fb_sp" "$FIRE_HOME/fire_builder/fire_builder.service" #included for future use
+			#sed -i "/WorkingDirectory/c $fb_rs" "$FIRE_HOME/fire_builder/fire_builder.service" #included for future use
 			sed -i "/User=changeMe/c $svc_user" "$FIRE_HOME/fire_builder/fire_builder.service"
 	
 			sudo cp "$FIRE_HOME/fire_builder/fire_builder.service" "/etc/systemd/system/fire_builder.service"
@@ -576,9 +555,9 @@ case "$MODE" in
 					HALLMARK=`getHallmark`
 					succeeded=$?
 					if [[ $succeeded ]]; then
-					echo $HALLMARK
 						if [[ "$HALLMARK" == *[!\ ]* ]]; then
 						 	done="true"
+						 	echo "Hallmark was set"
 						else
 							echo "unable to obtain hallmark"
 						fi
